name: metralab
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  easy_localization: ^2.3.2
  flutter_sparkline: ^0.1.0
  linalg: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_riverpod: ^0.12.1
  pedantic: ^1.9.2
  test: ^1.15.7

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
