jobs:
  build:
    docker:
      - image: ggiuffre/metralab-cicd # machine: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: flutter build appbundle
      - run: flutter channel beta
      - run: flutter upgrade
      - run: flutter config --enable-web
      - run: flutter create .
      - run: flutter build web
